config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :temperature_setting, except: [:destroy]

  root "weatherapp#home"
  get "/home", to: "weatherapp#home"
  get "/search", to: "weatherapp#search"
end

app/models/application_record.rb
# frozen_string_literal: true

# rubocop:disable Style/Documentation
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
# rubocop:enable Style/Documentation

app/models/temperature_setting.rb
# frozen_string_literal: true

class TemperatureSetting < ActiveRecord::Base
  validates :cold_temperature, presence: true
  validates :cold_temperature, numericality: { less_than: :warm_temperature }
  validates :cold_temperature, numericality: { less_than: :hot_temperature }
  validates :warm_temperature, presence: true
  validates :warm_temperature, numericality: { less_than: :hot_temperature }
  validates :warm_temperature, numericality: { greater_than: :cold_temperature }
  validates :hot_temperature, presence: true
  validates :hot_temperature, numericality: { greater_than: :cold_temperature }
  validates :hot_temperature, numericality: { greater_than: :warm_temperature }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/temperature_settings_controller.rb
# frozen_string_literal: true

# This Controller is for handling TemperatureSetting Model CRUD
class TemperatureSettingsController < ActionController::Base
  def show
    @temperature_setting = TemperatureSetting.first
  end

  def new
    @temperature_setting = TemperatureSetting.new
  end

  def edit
    @temperature_setting = TemperatureSetting.first
  end

  def create
    @temperature_setting = TemperatureSetting.new(temperature_setting_params)

    if @temperature_setting.save
      redirect_to @temperature_setting
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @temperature_setting = TemperatureSetting.first
    if @temperature_setting.update(temperature_setting_params)
      redirect_to @temperature_setting
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def temperature_setting_params
    params.require(:temperature_setting).permit(:cold_temperature, :warm_temperature, :hot_temperature)
  end
end

app/controllers/weatherapp_controller.rb
class WeatherappController < ActionController::Base

  require './app/services/postcode_checker'
  require './app/services/weather_search'
  require './app/services/temperature_calculator'

  def home

  end

  def search
    postcode = params[:query]
    if PostcodeChecker.uk_postcode_check postcode
      json = WeatherSearch.search_by_postcode postcode
      temperature = WeatherSearch.extract_temperature_from_json json
      @result = TemperatureCalculator.how_hot_is_it temperature
    else
      @result = "Invalid postcode"
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# rubocop:disable Style/Documentation
module ApplicationHelper
end
# rubocop:enable Style/Documentation

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/temperature_settings/_form.html.erb
<%= form_for :temperature_setting, url: ur do |form| %>
  <% if :temperature_setting.errors.any? %>
    <h2><%= pluralize(:temperature_setting.errors.count, "error") %> preventing these settings being saved:<h2>
      <ul>
        <% :temperature_setting.errors.each do |error| %>
          <li>error.full_message</li>
        <% end %>
      </ul>
    </h2>
  <% end %>

  <%= form.label :cold_temperature %>
  <%= form.range_field :cold_temperature, in: -200..200 %>

<% end %>

app/views/temperature_settings/edit.html.erb
<h1>Edit Temperature Settings</h1>

<%= form_with model: @temperature_setting, url: temperature_setting_path, method: 'patch' do |form| %>
  <% if @temperature_setting.errors.any? %>
    <h2><%= pluralize(@temperature_setting.errors.count, "error") %> preventing these settings being saved:
      <h2>
        <ul>
          <% @temperature_setting.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </h2>
  <% end %>

  <%= form.label :cold_temperature %>
  <%= form.number_field :cold_temperature, in: -200..200 %>
  <br>
  <%= form.label :warm_temperature %>
  <%= form.number_field :warm_temperature, in: -200..200 %>
  <br>
  <%= form.label :hot_temperature %>
  <%= form.number_field :hot_temperature, in: -200..200 %>
  <br>
  <%= form.submit %>
<% end %>

<%= link_to 'back', temperature_setting_path %>

app/views/temperature_settings/new.html.erb
<h1>New Temperature Settings</h1>

<% if TemperatureSetting.count < 1%>
  <%= form_with model: @temperature_setting, url: temperature_setting_path, method: 'post' do |form| %>
    <% if @temperature_setting.errors.any? %>
      <h2><%= pluralize(@temperature_setting.errors.count, "error") %> preventing these settings being saved:<h2>
        <ul>
          <% @temperature_setting.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </h2>
    <% end %>

    <%= form.label :cold_temperature %>
    <%= form.number_field :cold_temperature, in: -200..200 %>
    <br>
    <%= form.label :warm_temperature %>
    <%= form.number_field :warm_temperature, in: -200..200 %>
    <br>
    <%= form.label :hot_temperature %>
    <%= form.number_field :hot_temperature, in: -200..200 %>
    <br>
    <%= form.submit %>
  <% end %>
<% else %>
  <h2>You cannot create another Temperature Setting</h2>
  <p>You can go to the Temperature Setting <%= link_to 'here', temperature_setting_path %></p>
<% end %>

<%= link_to 'back', temperature_setting_path %>

app/views/temperature_settings/show.html.erb
<h1>Temperature Settings</h1>

<% if !@temperature_setting.nil? %>
  <h2>Cold Temperature: <%= @temperature_setting.cold_temperature %></h2>
  <h2>Warm Temperature: <%= @temperature_setting.warm_temperature %></h2>
  <h2>Hot Temperature: <%= @temperature_setting.hot_temperature %></h2>
  <p>You can edit temperature settings <%= link_to 'here', edit_temperature_setting_path %></p>
<% else %>
  <h2>Temperature Settings have not been defined</h2>
  <p>You can define temperature settings <%= link_to 'here', new_temperature_setting_path %></p>
<% end %>
<%= link_to 'back', '/home' %>

app/views/weatherapp/home.html.erb
<%= form_with url: "/search", method: :get do |form| %>
  <%= form.label :query, "Postcode Search:" %>
  <%= form.text_field :query, required: true %>
  <%= form.submit "Search" %>
<% end %>

<%= link_to 'Temperature Settings', temperature_setting_path %>

app/views/weatherapp/search.html.erb
<h2><%= "#{params[:query].blank? ? 'Invalid search' : params[:query]} is currently #{@result}" %></h2>
<br>
<%= link_to 'back', '/home' %>